### ISSUE TITLE
Navbar problems

### ISSUE THREAD

**Issue by k0msenapati** [PIYUSH1525/WEBSITE-NOTES#1]
It lacks a home page link.
The nav bar of syllabus.html is not working.

**Comment by PIYUSH1525** [comment]
Kindly attach the necessary screenshots

**Comment by PIYUSH1525** [comment]
ASSIGNED TO @kom-senapati 
SIMPLE - 10
(IF YOU CAN FIX THE RESPONSIVENESS I WILL MARK THIS ISSUE AS HARD )

**Comment by PIYUSH1525** [comment]
.take

**Comment by k0msenapati** [comment]
I cant work on responsiveness. I have made the navbar work again and also made dark mode functional. See #2

**Comment by PIYUSH1525** [comment]
Ok , Don’t forget to star the repository.
